name: echo demo
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: move to root
        run: |
          sshpass -p ${{secrets.SECRET}} ssh -o StrictHostKeyChecking=no ${{secrets.USER}}@${{secrets.HOST}} 'bash /data/scripts/rsync_github_to_gitlab.sh'
